# Generated by Django 4.2.7 on 2023-11-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0002_remove_domain_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(verbose_name='Date of expiry'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(verbose_name='Date registered'),
        ),
    ]
