# Generated by Django 4.2.7 on 2023-11-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_app', '0003_alter_domain_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='expiry_date',
            field=models.DateTimeField(null=True, verbose_name='Date of expiry'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='registration_date',
            field=models.DateTimeField(null=True, verbose_name='Date registered'),
        ),
    ]
